CREATE DATABASE Marketplace;

USE Marketplace;

CREATE TABLE Location(
    LocationID int NOT NULL AUTO_INCREMENT,
    City VARCHAR(100) NOT NULL,
    State VARCHAR(100) NOT NULL,
    Country VARCHAR(100) NOT NULL,
    PRIMARY KEY (LocationID)
);

CREATE TABLE User(
UserID INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
locationID INT DEFAULT NULL,
PRIMARY KEY (UserID),
UNIQUE KEY (email),
FOREIGN KEY (locationID) REFERENCES Location(LocationID)
);

CREATE TABLE BookInfo(
    BookInfoID INT NOT NULL AUTO_INCREMENT,
    Title VARCHAR(100) NOT NULL,
    Author VARCHAR(100) NOT NULL,
    ISBN VARCHAR(100) NOT NULL,
    PRIMARY KEY (BookInfoID)
);

CREATE TABLE BookListings(
    BookID INT NOT NULL AUTO_INCREMENT,
    ListingDate DATETIME NOT NULL,
    Price FLOAT NOT NULL,
    BookInfoID
    PRIMARY KEY (BookID),
    FOREIGN KEY (BookInfoID) REFERENCES BookInfo(BookInfoID),
    FOREIGN KEY (SellerID) REFERENCES User(UserID)
);

CREATE TABLE Purchases(
    PurchaseID INT NOT NULL AUTO_INCREMENT,
    PurchaseDate DATETIME NOT NULL,
    FOREIGN KEY (BuyerID) REFERENCES User(UserID),
    FOREIGN KEY (BookID) REFERENCES BookListings(BookID)
);