CREATE DATABASE Marketplace;

USE Marketplace;

CREATE TABLE User(
UserID int NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
locationID int DEFAULT NULL,
PRIMARY KEY (UserID),
UNIQUE KEY (email),
FOREIGN KEY (locationID) REFERENCES Locations(LocationID)
);


CREATE TABLE Location(
    LocationID int NOT NULL AUTO_INCREMENT,
    City VARCHAR(100)
)